const AboutView = () => {
  return (
    <div className='landing'>
      <h1>About the Spotify Blindtest</h1>
      <p>The Spotify Blindtest is not affiliated in any way to Spotify.</p>
      <p>
        Upon authorizing the application, the user can choose between his own
        playlists and others generated by the Spotify API. The user can choose
        between different game mode.
      </p>
      <p>The score is not saved after the game.</p>
      <p>
        This is my first web project and will not receive any more modification.
        If you want to see the code, it is available on my{' '}
        <a
          href='https://github.com/louis-tamagny/spotify-blindtest'
          target='__blank'>
          github page
        </a>
      </p>
    </div>
  )
}

export default AboutView
